{{- if and .Values.config.adminToken (not .Values.config.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermesgate.fullname" . }}
  labels:
    {{- include "hermesgate.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_TOKEN: {{ .Values.config.adminToken | b64enc | quote }}
{{- end }}
